"""
PlayCompass Activity Catalog Data

Contains the same 130+ activities as the mobile app for server-side filtering.
This allows the recommendation engine to run on the backend.
"""

from .models import Activity, AgeGroup, Category, Location, Duration, EnergyLevel, Materials


def create_activity(**kwargs) -> dict:
    """Helper to create activity dict with defaults."""
    return {
        "id": kwargs.get("id"),
        "title": kwargs.get("title"),
        "description": kwargs.get("description"),
        "emoji": kwargs.get("emoji"),
        "category": kwargs.get("category"),
        "age_groups": kwargs.get("age_groups", []),
        "location": kwargs.get("location", "indoor"),
        "duration": kwargs.get("duration"),
        "energy": kwargs.get("energy"),
        "materials": kwargs.get("materials", "none"),
        "participants": kwargs.get("participants", "any"),
        "interests": kwargs.get("interests", []),
        "tags": kwargs.get("tags", []),
        "weather": kwargs.get("weather", "any"),
        "instructions": kwargs.get("instructions", []),
        "tips": kwargs.get("tips", []),
        "variations": kwargs.get("variations", []),
        "adult_supervision": kwargs.get("adult_supervision", False),
        "popularity_score": kwargs.get("popularity_score", 50),
    }


# Activity catalog - matching mobile app data
ACTIVITIES = [
    # ============================================
    # ACTIVE PLAY (20 activities)
    # ============================================
    create_activity(
        id="act_001",
        title="Dance Party",
        description="Put on favorite music and have a fun dance session together",
        emoji="💃",
        category="active",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="high",
        materials="tech",
        interests=["music", "dance"],
        tags=["music", "exercise", "fun", "energy-burner"],
        popularity_score=95,
    ),
    create_activity(
        id="act_002",
        title="Obstacle Course",
        description="Create an indoor obstacle course using pillows, chairs, and blankets",
        emoji="🏃",
        category="active",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="medium",
        energy="high",
        materials="basic",
        interests=["sports"],
        tags=["gross-motor", "creative", "energy-burner"],
        popularity_score=90,
    ),
    create_activity(
        id="act_003",
        title="Bike Riding",
        description="Go for a bike ride around the neighborhood or local trail",
        emoji="🚴",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="medium",
        energy="high",
        materials="sports",
        interests=["sports", "nature"],
        tags=["exercise", "outdoor", "transportation"],
        weather="sunny",
        adult_supervision=True,
        popularity_score=88,
    ),
    create_activity(
        id="act_004",
        title="Hide and Seek",
        description="Classic game of hiding and seeking around the house or yard",
        emoji="🙈",
        category="active",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="both",
        duration="short",
        energy="medium",
        materials="none",
        participants="small_group",
        interests=["games"],
        tags=["classic", "no-prep", "group"],
        popularity_score=92,
    ),
    create_activity(
        id="act_005",
        title="Soccer in the Backyard",
        description="Practice soccer skills or play a casual game",
        emoji="⚽",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="medium",
        energy="high",
        materials="sports",
        interests=["sports"],
        tags=["sports", "team", "exercise"],
        weather="sunny",
        popularity_score=85,
    ),
    create_activity(
        id="act_006",
        title="Freeze Dance",
        description="Dance when music plays, freeze when it stops!",
        emoji="🕺",
        category="active",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="high",
        materials="tech",
        interests=["music", "dance"],
        tags=["music", "game", "party"],
        popularity_score=88,
    ),
    create_activity(
        id="act_007",
        title="Balloon Volleyball",
        description="Play volleyball with a balloon - safe indoor fun!",
        emoji="🎈",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="medium",
        materials="basic",
        interests=["sports"],
        tags=["safe", "indoor-sports", "party"],
        popularity_score=82,
    ),
    create_activity(
        id="act_008",
        title="Swimming",
        description="Go for a swim at the pool or beach",
        emoji="🏊",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="long",
        energy="high",
        materials="special",
        interests=["sports"],
        tags=["summer", "water", "exercise"],
        weather="warm",
        adult_supervision=True,
        popularity_score=90,
    ),
    create_activity(
        id="act_009",
        title="Tag Games",
        description="Play various tag games like freeze tag or TV tag",
        emoji="🏷️",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="outdoor",
        duration="short",
        energy="high",
        materials="none",
        participants="small_group",
        interests=["sports", "games"],
        tags=["classic", "running", "group"],
        popularity_score=87,
    ),
    create_activity(
        id="act_010",
        title="Jump Rope",
        description="Practice jump rope skills or play jump rope games",
        emoji="🪢",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="both",
        duration="short",
        energy="high",
        materials="sports",
        interests=["sports"],
        tags=["exercise", "coordination", "classic"],
        popularity_score=78,
    ),
    create_activity(
        id="act_011",
        title="Yoga for Kids",
        description="Follow along with kid-friendly yoga poses and stretches",
        emoji="🧘",
        category="active",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="none",
        interests=["sports"],
        tags=["mindfulness", "flexibility", "calm"],
        popularity_score=75,
    ),
    create_activity(
        id="act_012",
        title="Basketball Practice",
        description="Shoot hoops and practice basketball skills",
        emoji="🏀",
        category="active",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="medium",
        energy="high",
        materials="sports",
        interests=["sports"],
        tags=["sports", "skills", "exercise"],
        weather="sunny",
        popularity_score=83,
    ),
    create_activity(
        id="act_013",
        title="Hula Hoop",
        description="Practice hula hooping and learn new tricks",
        emoji="⭕",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary"],
        location="both",
        duration="short",
        energy="medium",
        materials="sports",
        interests=["sports", "dance"],
        tags=["coordination", "fun", "exercise"],
        popularity_score=70,
    ),
    create_activity(
        id="act_014",
        title="Scavenger Hunt",
        description="Search for items on a list around the house or outdoors",
        emoji="🔍",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="both",
        duration="medium",
        energy="medium",
        materials="basic",
        interests=["nature", "games"],
        tags=["adventure", "exploration", "problem-solving"],
        popularity_score=89,
    ),
    create_activity(
        id="act_015",
        title="Trampoline Time",
        description="Jump and play on the trampoline",
        emoji="🤸",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="outdoor",
        duration="medium",
        energy="high",
        materials="special",
        interests=["sports"],
        tags=["jumping", "energy-burner", "fun"],
        adult_supervision=True,
        popularity_score=86,
    ),
    create_activity(
        id="act_016",
        title="Pillow Fight",
        description="Safe and fun pillow fight with soft pillows",
        emoji="🛏️",
        category="active",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="quick",
        energy="high",
        materials="basic",
        interests=["games"],
        tags=["silly", "energy-burner", "bonding"],
        popularity_score=80,
    ),
    create_activity(
        id="act_017",
        title="Roller Skating",
        description="Go roller skating or practice at home",
        emoji="🛼",
        category="active",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="both",
        duration="medium",
        energy="high",
        materials="sports",
        interests=["sports"],
        tags=["skills", "exercise", "coordination"],
        adult_supervision=True,
        popularity_score=72,
    ),
    create_activity(
        id="act_018",
        title="Catch",
        description="Play catch with a ball, frisbee, or soft toy",
        emoji="🥎",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="short",
        energy="medium",
        materials="sports",
        interests=["sports"],
        tags=["classic", "bonding", "coordination"],
        popularity_score=81,
    ),
    create_activity(
        id="act_019",
        title="Simon Says",
        description="Classic game of following commands only when Simon says",
        emoji="🗣️",
        category="active",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="medium",
        materials="none",
        participants="small_group",
        interests=["games"],
        tags=["listening", "classic", "group"],
        popularity_score=84,
    ),
    create_activity(
        id="act_020",
        title="Hiking",
        description="Go on a nature hike on a local trail",
        emoji="🥾",
        category="active",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="long",
        energy="medium",
        materials="none",
        interests=["nature", "sports"],
        tags=["nature", "adventure", "exercise"],
        weather="sunny",
        adult_supervision=True,
        popularity_score=79,
    ),

    # ============================================
    # CREATIVE (25 activities)
    # ============================================
    create_activity(
        id="cre_001",
        title="Drawing & Coloring",
        description="Express creativity through drawing and coloring",
        emoji="🖍️",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["art", "quiet", "imagination"],
        popularity_score=94,
    ),
    create_activity(
        id="cre_002",
        title="Play-Doh Creations",
        description="Mold and create with Play-Doh or homemade clay",
        emoji="🎨",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["sensory", "sculpture", "fine-motor"],
        popularity_score=91,
    ),
    create_activity(
        id="cre_003",
        title="Building with Blocks",
        description="Construct towers, buildings, and creations with blocks",
        emoji="🧱",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["building"],
        tags=["construction", "imagination", "problem-solving"],
        popularity_score=90,
    ),
    create_activity(
        id="cre_004",
        title="LEGO Building",
        description="Create anything imaginable with LEGO bricks",
        emoji="🏗️",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="special",
        interests=["building"],
        tags=["construction", "following-instructions", "imagination"],
        popularity_score=93,
    ),
    create_activity(
        id="cre_005",
        title="Painting",
        description="Create art with watercolors, finger paints, or acrylics",
        emoji="🎨",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["art", "messy", "expression"],
        popularity_score=88,
    ),
    create_activity(
        id="cre_006",
        title="Paper Crafts",
        description="Make origami, paper airplanes, or cut-out crafts",
        emoji="📄",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["folding", "fine-motor", "crafts"],
        popularity_score=80,
    ),
    create_activity(
        id="cre_007",
        title="Jewelry Making",
        description="Create bracelets, necklaces, and accessories",
        emoji="📿",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["beading", "fine-motor", "wearable-art"],
        popularity_score=76,
    ),
    create_activity(
        id="cre_008",
        title="Dress-Up & Pretend Play",
        description="Use costumes and props for imaginative role-playing",
        emoji="👑",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="medium",
        energy="medium",
        materials="basic",
        interests=["art", "games"],
        tags=["imagination", "social", "costumes"],
        popularity_score=89,
    ),
    create_activity(
        id="cre_009",
        title="Puppet Show",
        description="Create puppets and put on a puppet show",
        emoji="🎭",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="long",
        energy="medium",
        materials="craft",
        interests=["art", "music"],
        tags=["performance", "storytelling", "crafts"],
        popularity_score=74,
    ),
    create_activity(
        id="cre_010",
        title="Collage Making",
        description="Create art by cutting and pasting from magazines",
        emoji="✂️",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["cutting", "composition", "recycling"],
        popularity_score=72,
    ),
    create_activity(
        id="cre_011",
        title="Face Painting",
        description="Paint fun designs on faces with safe face paint",
        emoji="🎭",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["party", "transformation", "fun"],
        popularity_score=83,
    ),
    create_activity(
        id="cre_012",
        title="Storytelling",
        description="Make up stories together or continue a story chain",
        emoji="📖",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="none",
        interests=["reading"],
        tags=["imagination", "language", "bonding"],
        popularity_score=78,
    ),
    create_activity(
        id="cre_013",
        title="Photography",
        description="Take photos and learn basic photography skills",
        emoji="📸",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="both",
        duration="medium",
        energy="low",
        materials="tech",
        interests=["art", "technology"],
        tags=["digital", "observation", "art"],
        popularity_score=75,
    ),
    create_activity(
        id="cre_014",
        title="Slime Making",
        description="Create colorful, stretchy slime",
        emoji="🧪",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["science", "art"],
        tags=["sensory", "science", "messy"],
        adult_supervision=True,
        popularity_score=87,
    ),
    create_activity(
        id="cre_015",
        title="Comic Book Creation",
        description="Draw and write your own comic book",
        emoji="💬",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="craft",
        interests=["art", "reading"],
        tags=["writing", "drawing", "storytelling"],
        popularity_score=73,
    ),
    create_activity(
        id="cre_016",
        title="Tie-Dye",
        description="Create colorful tie-dye shirts and crafts",
        emoji="🌈",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="long",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["messy", "colorful", "wearable"],
        adult_supervision=True,
        popularity_score=79,
    ),
    create_activity(
        id="cre_017",
        title="Finger Painting",
        description="Get messy with hands-on finger painting",
        emoji="🖐️",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["sensory", "messy", "tactile"],
        popularity_score=85,
    ),
    create_activity(
        id="cre_018",
        title="Building a Fort",
        description="Construct a fort with blankets, pillows, and furniture",
        emoji="🏰",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="medium",
        energy="medium",
        materials="basic",
        interests=["building"],
        tags=["imagination", "cozy", "construction"],
        popularity_score=91,
    ),
    create_activity(
        id="cre_019",
        title="Sewing & Needlework",
        description="Learn basic sewing, knitting, or cross-stitch",
        emoji="🧵",
        category="creative",
        age_groups=["late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["skills", "patience", "crafts"],
        popularity_score=65,
    ),
    create_activity(
        id="cre_020",
        title="Cardboard Creations",
        description="Build things from cardboard boxes and tubes",
        emoji="📦",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="long",
        energy="medium",
        materials="basic",
        interests=["building", "art"],
        tags=["recycling", "construction", "imagination"],
        popularity_score=77,
    ),
    create_activity(
        id="cre_021",
        title="Decorating Cookies",
        description="Decorate pre-made cookies with icing and sprinkles",
        emoji="🍪",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="kitchen",
        interests=["cooking", "art"],
        tags=["food", "decorating", "tasty"],
        popularity_score=88,
    ),
    create_activity(
        id="cre_022",
        title="Sand Art",
        description="Create art with colored sand in bottles or on paper",
        emoji="🏖️",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["sensory", "colorful", "patience"],
        popularity_score=71,
    ),
    create_activity(
        id="cre_023",
        title="Writing Stories",
        description="Write original short stories or journal entries",
        emoji="✍️",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["writing", "imagination", "language"],
        popularity_score=70,
    ),
    create_activity(
        id="cre_024",
        title="Flower Pressing",
        description="Press and preserve flowers to create art",
        emoji="🌸",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="extended",
        energy="low",
        materials="basic",
        interests=["nature", "art"],
        tags=["nature", "patience", "decoration"],
        popularity_score=62,
    ),
    create_activity(
        id="cre_025",
        title="DIY Room Decor",
        description="Make decorations for your room",
        emoji="🎀",
        category="creative",
        age_groups=["late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["personalization", "crafts", "room"],
        popularity_score=74,
    ),

    # ============================================
    # EDUCATIONAL (25 activities)
    # ============================================
    create_activity(
        id="edu_001",
        title="Reading Time",
        description="Read books together or independently",
        emoji="📚",
        category="educational",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["literacy", "quiet", "learning"],
        popularity_score=92,
    ),
    create_activity(
        id="edu_002",
        title="Science Experiments",
        description="Do fun, safe science experiments at home",
        emoji="🔬",
        category="educational",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["science"],
        tags=["STEM", "discovery", "hands-on"],
        adult_supervision=True,
        popularity_score=89,
    ),
    create_activity(
        id="edu_003",
        title="Puzzle Time",
        description="Work on jigsaw puzzles or brain teasers",
        emoji="🧩",
        category="educational",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["games"],
        tags=["problem-solving", "patience", "focus"],
        popularity_score=86,
    ),
    create_activity(
        id="edu_004",
        title="Math Games",
        description="Play fun games that practice math skills",
        emoji="🔢",
        category="educational",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["science"],
        tags=["math", "learning", "games"],
        popularity_score=72,
    ),
    create_activity(
        id="edu_005",
        title="Nature Journal",
        description="Observe and draw plants, animals, and nature",
        emoji="🌿",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["nature", "art", "science"],
        tags=["observation", "science", "art"],
        popularity_score=70,
    ),
    create_activity(
        id="edu_006",
        title="Coding for Kids",
        description="Learn programming with kid-friendly apps and games",
        emoji="💻",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="tech",
        interests=["technology", "science"],
        tags=["STEM", "programming", "logic"],
        popularity_score=81,
    ),
    create_activity(
        id="edu_007",
        title="Flashcard Review",
        description="Practice facts with flashcards - letters, numbers, vocabulary",
        emoji="🃏",
        category="educational",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["memory", "learning", "practice"],
        popularity_score=68,
    ),
    create_activity(
        id="edu_008",
        title="Documentary Watching",
        description="Watch educational documentaries about nature, science, or history",
        emoji="🎬",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="tech",
        interests=["science", "nature"],
        tags=["screen-time", "learning", "discussion"],
        popularity_score=75,
    ),
    create_activity(
        id="edu_009",
        title="Geography Games",
        description="Learn about countries, capitals, and maps",
        emoji="🗺️",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["science"],
        tags=["geography", "maps", "world"],
        popularity_score=67,
    ),
    create_activity(
        id="edu_010",
        title="Bird Watching",
        description="Observe and identify birds in your area",
        emoji="🐦",
        category="educational",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["nature", "animals"],
        tags=["nature", "observation", "patience"],
        popularity_score=64,
    ),
    create_activity(
        id="edu_011",
        title="Building Models",
        description="Construct model kits - planes, cars, buildings",
        emoji="✈️",
        category="educational",
        age_groups=["late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="special",
        interests=["building", "science"],
        tags=["following-instructions", "patience", "detail"],
        popularity_score=71,
    ),
    create_activity(
        id="edu_012",
        title="Learning a Language",
        description="Practice a new language with apps, videos, or books",
        emoji="🗣️",
        category="educational",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="tech",
        interests=["reading"],
        tags=["language", "culture", "skills"],
        popularity_score=73,
    ),
    create_activity(
        id="edu_013",
        title="Counting Games",
        description="Practice counting with fun games and activities",
        emoji="🔢",
        category="educational",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["science"],
        tags=["math", "early-learning", "numbers"],
        popularity_score=80,
    ),
    create_activity(
        id="edu_014",
        title="Spelling Bee Practice",
        description="Practice spelling words and have spelling challenges",
        emoji="📝",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["spelling", "vocabulary", "competition"],
        popularity_score=65,
    ),
    create_activity(
        id="edu_015",
        title="Star Gazing",
        description="Observe stars and constellations at night",
        emoji="⭐",
        category="educational",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="medium",
        energy="low",
        materials="none",
        interests=["science", "nature"],
        tags=["astronomy", "night", "wonder"],
        adult_supervision=True,
        popularity_score=78,
    ),
    create_activity(
        id="edu_016",
        title="Gardening",
        description="Plant and care for seeds, flowers, or vegetables",
        emoji="🌱",
        category="educational",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="outdoor",
        duration="medium",
        energy="medium",
        materials="special",
        interests=["nature", "science"],
        tags=["plants", "responsibility", "nature"],
        popularity_score=77,
    ),
    create_activity(
        id="edu_017",
        title="Trivia Games",
        description="Test knowledge with trivia questions",
        emoji="❓",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="none",
        participants="small_group",
        interests=["games"],
        tags=["knowledge", "competition", "fun"],
        popularity_score=76,
    ),
    create_activity(
        id="edu_018",
        title="Museum Virtual Tour",
        description="Take virtual tours of famous museums online",
        emoji="🏛️",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="tech",
        interests=["art", "science"],
        tags=["virtual", "culture", "exploration"],
        popularity_score=69,
    ),
    create_activity(
        id="edu_019",
        title="Letter Practice",
        description="Practice writing letters and words",
        emoji="✏️",
        category="educational",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["writing", "fine-motor", "literacy"],
        popularity_score=82,
    ),
    create_activity(
        id="edu_020",
        title="Building Circuits",
        description="Learn about electricity with safe circuit kits",
        emoji="⚡",
        category="educational",
        age_groups=["late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="special",
        interests=["science", "technology"],
        tags=["STEM", "electronics", "hands-on"],
        adult_supervision=True,
        popularity_score=74,
    ),
    create_activity(
        id="edu_021",
        title="Sorting & Categorizing",
        description="Sort objects by color, shape, size, or type",
        emoji="📊",
        category="educational",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["science"],
        tags=["logic", "early-learning", "organization"],
        popularity_score=75,
    ),
    create_activity(
        id="edu_022",
        title="Typing Practice",
        description="Learn and practice keyboard typing skills",
        emoji="⌨️",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="tech",
        interests=["technology"],
        tags=["computer", "skills", "practice"],
        popularity_score=66,
    ),
    create_activity(
        id="edu_023",
        title="Microscope Exploration",
        description="Examine small objects under a microscope",
        emoji="🔬",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="special",
        interests=["science"],
        tags=["science", "discovery", "observation"],
        popularity_score=72,
    ),
    create_activity(
        id="edu_024",
        title="History Stories",
        description="Learn about historical events through stories and books",
        emoji="📜",
        category="educational",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["history", "stories", "learning"],
        popularity_score=68,
    ),
    create_activity(
        id="edu_025",
        title="Weather Observation",
        description="Track and record daily weather patterns",
        emoji="🌤️",
        category="educational",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="both",
        duration="quick",
        energy="low",
        materials="basic",
        interests=["science", "nature"],
        tags=["weather", "observation", "recording"],
        popularity_score=63,
    ),

    # ============================================
    # CALM/QUIET (15 activities)
    # ============================================
    create_activity(
        id="calm_001",
        title="Meditation for Kids",
        description="Practice simple breathing and mindfulness exercises",
        emoji="🧘",
        category="calm",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="none",
        interests=["sports"],
        tags=["mindfulness", "relaxation", "breathing"],
        popularity_score=70,
    ),
    create_activity(
        id="calm_002",
        title="Listening to Audiobooks",
        description="Listen to stories and audiobooks",
        emoji="🎧",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="tech",
        interests=["reading"],
        tags=["stories", "imagination", "quiet"],
        popularity_score=79,
    ),
    create_activity(
        id="calm_003",
        title="Sensory Bin Play",
        description="Explore textures with rice, beans, sand, or water beads",
        emoji="🫘",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["science"],
        tags=["sensory", "exploration", "calming"],
        popularity_score=83,
    ),
    create_activity(
        id="calm_004",
        title="Cloud Watching",
        description="Lie back and find shapes in the clouds",
        emoji="☁️",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school"],
        location="outdoor",
        duration="short",
        energy="low",
        materials="none",
        interests=["nature"],
        tags=["imagination", "relaxation", "nature"],
        weather="sunny",
        popularity_score=72,
    ),
    create_activity(
        id="calm_005",
        title="Listening to Music",
        description="Relax and listen to calming or favorite music",
        emoji="🎵",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="tech",
        interests=["music"],
        tags=["relaxation", "mood", "quiet"],
        popularity_score=81,
    ),
    create_activity(
        id="calm_006",
        title="Coloring Books",
        description="Color in coloring books or printable pages",
        emoji="🖍️",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["relaxing", "art", "focus"],
        popularity_score=88,
    ),
    create_activity(
        id="calm_007",
        title="Journaling",
        description="Write thoughts, feelings, or daily events in a journal",
        emoji="📓",
        category="calm",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["writing", "reflection", "emotions"],
        popularity_score=67,
    ),
    create_activity(
        id="calm_008",
        title="Bath Time Fun",
        description="Enjoy bath time with toys, bubbles, and bath bombs",
        emoji="🛁",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["science"],
        tags=["water", "relaxation", "routine"],
        adult_supervision=True,
        popularity_score=80,
    ),
    create_activity(
        id="calm_009",
        title="Quiet Reading Corner",
        description="Set up a cozy spot for quiet reading time",
        emoji="📖",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["cozy", "quiet", "literacy"],
        popularity_score=84,
    ),
    create_activity(
        id="calm_010",
        title="Gentle Stretching",
        description="Do simple stretches to relax the body",
        emoji="🙆",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="quick",
        energy="low",
        materials="none",
        interests=["sports"],
        tags=["flexibility", "relaxation", "body"],
        popularity_score=69,
    ),
    create_activity(
        id="calm_011",
        title="Bedtime Stories",
        description="Read calming stories before bedtime",
        emoji="🌙",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["routine", "bonding", "sleep"],
        popularity_score=90,
    ),
    create_activity(
        id="calm_012",
        title="Watching Fish",
        description="Observe fish in an aquarium or fish tank video",
        emoji="🐠",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="tech",
        interests=["animals", "nature"],
        tags=["observation", "calming", "nature"],
        popularity_score=65,
    ),
    create_activity(
        id="calm_013",
        title="Dot-to-Dot",
        description="Complete dot-to-dot puzzles to reveal pictures",
        emoji="✏️",
        category="calm",
        age_groups=["preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["art"],
        tags=["numbers", "focus", "drawing"],
        popularity_score=71,
    ),
    create_activity(
        id="calm_014",
        title="Relaxation Sounds",
        description="Listen to nature sounds or white noise",
        emoji="🌊",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="tech",
        interests=["music", "nature"],
        tags=["calming", "sleep", "relaxation"],
        popularity_score=66,
    ),
    create_activity(
        id="calm_015",
        title="Sticker Activities",
        description="Create pictures and scenes with stickers",
        emoji="⭐",
        category="calm",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="craft",
        interests=["art"],
        tags=["fine-motor", "quiet", "creative"],
        popularity_score=82,
    ),

    # ============================================
    # MUSIC (10 activities)
    # ============================================
    create_activity(
        id="mus_001",
        title="Sing-Along Time",
        description="Sing favorite songs together as a family",
        emoji="🎤",
        category="music",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="medium",
        materials="none",
        interests=["music"],
        tags=["singing", "bonding", "fun"],
        popularity_score=87,
    ),
    create_activity(
        id="mus_002",
        title="Musical Instruments",
        description="Play real or homemade musical instruments",
        emoji="🥁",
        category="music",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="medium",
        materials="special",
        interests=["music"],
        tags=["instruments", "rhythm", "creativity"],
        popularity_score=83,
    ),
    create_activity(
        id="mus_003",
        title="Karaoke",
        description="Have a karaoke session with favorite songs",
        emoji="🎙️",
        category="music",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="medium",
        materials="tech",
        interests=["music"],
        tags=["singing", "performance", "party"],
        popularity_score=85,
    ),
    create_activity(
        id="mus_004",
        title="Rhythm Games",
        description="Clap, tap, and move to different rhythms",
        emoji="👏",
        category="music",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="medium",
        materials="none",
        interests=["music", "dance"],
        tags=["rhythm", "coordination", "fun"],
        popularity_score=79,
    ),
    create_activity(
        id="mus_005",
        title="Music and Movement",
        description="Move and dance freely to different types of music",
        emoji="💃",
        category="music",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="high",
        materials="tech",
        interests=["music", "dance"],
        tags=["movement", "expression", "energy"],
        popularity_score=86,
    ),
    create_activity(
        id="mus_006",
        title="Learn a Song",
        description="Learn the words and melody to a new song",
        emoji="🎵",
        category="music",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="tech",
        interests=["music"],
        tags=["learning", "memory", "singing"],
        popularity_score=74,
    ),
    create_activity(
        id="mus_007",
        title="Making Instruments",
        description="Create DIY instruments from household items",
        emoji="🪘",
        category="music",
        age_groups=["preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["music", "art", "building"],
        tags=["crafts", "creativity", "recycling"],
        popularity_score=76,
    ),
    create_activity(
        id="mus_008",
        title="Musical Chairs",
        description="Classic party game with music",
        emoji="🪑",
        category="music",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="medium",
        materials="basic",
        participants="small_group",
        interests=["music", "games"],
        tags=["party", "game", "active"],
        popularity_score=84,
    ),
    create_activity(
        id="mus_009",
        title="Song Writing",
        description="Create original songs with lyrics and melodies",
        emoji="🎼",
        category="music",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="basic",
        interests=["music"],
        tags=["creativity", "writing", "composition"],
        popularity_score=68,
    ),
    create_activity(
        id="mus_010",
        title="Music Appreciation",
        description="Listen to and discuss different types of music",
        emoji="🎶",
        category="music",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="tech",
        interests=["music"],
        tags=["listening", "culture", "discussion"],
        popularity_score=64,
    ),

    # ============================================
    # GAMES (15 activities)
    # ============================================
    create_activity(
        id="gam_001",
        title="Board Games",
        description="Play classic or new board games together",
        emoji="🎲",
        category="games",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="special",
        participants="small_group",
        interests=["games"],
        tags=["family", "strategy", "fun"],
        popularity_score=91,
    ),
    create_activity(
        id="gam_002",
        title="Card Games",
        description="Play card games like Go Fish, Uno, or War",
        emoji="🃏",
        category="games",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["games"],
        tags=["cards", "strategy", "family"],
        popularity_score=88,
    ),
    create_activity(
        id="gam_003",
        title="Video Games (Educational)",
        description="Play age-appropriate educational video games",
        emoji="🎮",
        category="games",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="tech",
        interests=["technology", "games"],
        tags=["screen-time", "learning", "fun"],
        popularity_score=85,
    ),
    create_activity(
        id="gam_004",
        title="Memory Games",
        description="Test memory with matching card games",
        emoji="🧠",
        category="games",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        interests=["games"],
        tags=["memory", "focus", "matching"],
        popularity_score=82,
    ),
    create_activity(
        id="gam_005",
        title="Charades",
        description="Act out words or phrases for others to guess",
        emoji="🎭",
        category="games",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="medium",
        materials="none",
        participants="small_group",
        interests=["games", "dance"],
        tags=["acting", "party", "team"],
        popularity_score=86,
    ),
    create_activity(
        id="gam_006",
        title="Dominoes",
        description="Play domino games or set up domino chains",
        emoji="🁑",
        category="games",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["games", "building"],
        tags=["patterns", "patience", "chain-reaction"],
        popularity_score=75,
    ),
    create_activity(
        id="gam_007",
        title="I Spy",
        description="Classic observation game spotting objects",
        emoji="👁️",
        category="games",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="both",
        duration="quick",
        energy="low",
        materials="none",
        interests=["games"],
        tags=["observation", "language", "travel"],
        popularity_score=83,
    ),
    create_activity(
        id="gam_008",
        title="20 Questions",
        description="Guess the object by asking yes/no questions",
        emoji="❓",
        category="games",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="both",
        duration="short",
        energy="low",
        materials="none",
        interests=["games"],
        tags=["thinking", "deduction", "travel"],
        popularity_score=77,
    ),
    create_activity(
        id="gam_009",
        title="Tic-Tac-Toe",
        description="Classic pen and paper strategy game",
        emoji="⭕",
        category="games",
        age_groups=["preschool", "early_elementary", "late_elementary"],
        location="indoor",
        duration="quick",
        energy="low",
        materials="basic",
        interests=["games"],
        tags=["strategy", "quick", "classic"],
        popularity_score=80,
    ),
    create_activity(
        id="gam_010",
        title="Jenga",
        description="Carefully remove blocks without toppling the tower",
        emoji="🧱",
        category="games",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="special",
        interests=["games"],
        tags=["dexterity", "suspense", "family"],
        popularity_score=84,
    ),
    create_activity(
        id="gam_011",
        title="Word Games",
        description="Play word games like Scrabble Jr or Boggle",
        emoji="📝",
        category="games",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="special",
        interests=["reading", "games"],
        tags=["vocabulary", "spelling", "thinking"],
        popularity_score=73,
    ),
    create_activity(
        id="gam_012",
        title="Rock Paper Scissors Tournament",
        description="Have a rock paper scissors championship",
        emoji="✊",
        category="games",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="quick",
        energy="low",
        materials="none",
        interests=["games"],
        tags=["quick", "classic", "tournament"],
        popularity_score=78,
    ),
    create_activity(
        id="gam_013",
        title="Bingo",
        description="Play bingo with numbers, pictures, or words",
        emoji="🎯",
        category="games",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="basic",
        participants="small_group",
        interests=["games"],
        tags=["numbers", "party", "chance"],
        popularity_score=76,
    ),
    create_activity(
        id="gam_014",
        title="Guess Who",
        description="Guess the mystery character by asking questions",
        emoji="🤔",
        category="games",
        age_groups=["early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="special",
        interests=["games"],
        tags=["deduction", "questions", "classic"],
        popularity_score=79,
    ),
    create_activity(
        id="gam_015",
        title="Marble Run",
        description="Build and race marble runs",
        emoji="🔮",
        category="games",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="special",
        interests=["building", "science"],
        tags=["building", "physics", "creativity"],
        popularity_score=81,
    ),

    # ============================================
    # SOCIAL (10 activities)
    # ============================================
    create_activity(
        id="soc_001",
        title="Playdate",
        description="Arrange a playdate with friends",
        emoji="👫",
        category="social",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school"],
        location="both",
        duration="long",
        energy="medium",
        materials="none",
        participants="small_group",
        interests=["games"],
        tags=["friends", "social", "play"],
        popularity_score=90,
    ),
    create_activity(
        id="soc_002",
        title="Tea Party",
        description="Host a pretend or real tea party",
        emoji="🫖",
        category="social",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["games"],
        tags=["pretend", "manners", "hosting"],
        popularity_score=78,
    ),
    create_activity(
        id="soc_003",
        title="Video Call with Family",
        description="Connect with distant family members via video call",
        emoji="📱",
        category="social",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="tech",
        interests=["technology"],
        tags=["family", "connection", "communication"],
        popularity_score=82,
    ),
    create_activity(
        id="soc_004",
        title="Show and Tell",
        description="Share favorite items and tell stories about them",
        emoji="🎁",
        category="social",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="none",
        interests=["reading"],
        tags=["sharing", "speaking", "presentation"],
        popularity_score=75,
    ),
    create_activity(
        id="soc_005",
        title="Cooperative Games",
        description="Play games where everyone works together to win",
        emoji="🤝",
        category="social",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="special",
        participants="small_group",
        interests=["games"],
        tags=["teamwork", "cooperation", "problem-solving"],
        popularity_score=80,
    ),
    create_activity(
        id="soc_006",
        title="Birthday Party Planning",
        description="Plan and organize a birthday celebration",
        emoji="🎂",
        category="social",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="medium",
        materials="basic",
        interests=["art"],
        tags=["planning", "celebration", "creativity"],
        popularity_score=77,
    ),
    create_activity(
        id="soc_007",
        title="Team Building Games",
        description="Play games that build teamwork and cooperation",
        emoji="🏆",
        category="social",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="both",
        duration="medium",
        energy="medium",
        materials="none",
        participants="small_group",
        interests=["games", "sports"],
        tags=["teamwork", "leadership", "cooperation"],
        popularity_score=74,
    ),
    create_activity(
        id="soc_008",
        title="Pen Pals",
        description="Write letters to pen pals near or far",
        emoji="✉️",
        category="social",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="basic",
        interests=["reading"],
        tags=["writing", "friendship", "communication"],
        popularity_score=65,
    ),
    create_activity(
        id="soc_009",
        title="Group Storytelling",
        description="Create stories together, each person adding a part",
        emoji="📚",
        category="social",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="none",
        participants="small_group",
        interests=["reading"],
        tags=["creativity", "listening", "collaboration"],
        popularity_score=72,
    ),
    create_activity(
        id="soc_010",
        title="Talent Show",
        description="Put on a talent show with family or friends",
        emoji="🌟",
        category="social",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="medium",
        materials="basic",
        participants="small_group",
        interests=["music", "dance", "art"],
        tags=["performance", "confidence", "celebration"],
        popularity_score=79,
    ),

    # ============================================
    # COOKING (10 activities - categorized as creative)
    # ============================================
    create_activity(
        id="cook_001",
        title="Baking Cookies",
        description="Bake and decorate homemade cookies",
        emoji="🍪",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="kitchen",
        interests=["cooking"],
        tags=["baking", "measuring", "delicious"],
        adult_supervision=True,
        popularity_score=92,
    ),
    create_activity(
        id="cook_002",
        title="Making Smoothies",
        description="Blend up healthy and tasty smoothies",
        emoji="🥤",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="kitchen",
        interests=["cooking"],
        tags=["healthy", "blending", "quick"],
        adult_supervision=True,
        popularity_score=85,
    ),
    create_activity(
        id="cook_003",
        title="Pizza Making",
        description="Make homemade pizza with favorite toppings",
        emoji="🍕",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="kitchen",
        interests=["cooking"],
        tags=["dinner", "customizable", "family"],
        adult_supervision=True,
        popularity_score=93,
    ),
    create_activity(
        id="cook_004",
        title="Sandwich Art",
        description="Create fun shaped sandwiches with cookie cutters",
        emoji="🥪",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary"],
        location="indoor",
        duration="short",
        energy="low",
        materials="kitchen",
        interests=["cooking", "art"],
        tags=["lunch", "shapes", "easy"],
        popularity_score=80,
    ),
    create_activity(
        id="cook_005",
        title="Fruit Kabobs",
        description="Make colorful fruit kabobs",
        emoji="🍓",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="kitchen",
        interests=["cooking"],
        tags=["healthy", "snack", "colorful"],
        adult_supervision=True,
        popularity_score=83,
    ),
    create_activity(
        id="cook_006",
        title="Pancake Art",
        description="Make fun shaped pancakes for breakfast",
        emoji="🥞",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="kitchen",
        interests=["cooking", "art"],
        tags=["breakfast", "shapes", "fun"],
        adult_supervision=True,
        popularity_score=86,
    ),
    create_activity(
        id="cook_007",
        title="No-Bake Treats",
        description="Make treats that don't require an oven",
        emoji="🍫",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="medium",
        energy="low",
        materials="kitchen",
        interests=["cooking"],
        tags=["safe", "treats", "easy"],
        popularity_score=84,
    ),
    create_activity(
        id="cook_008",
        title="Cooking with a Recipe",
        description="Follow a kid-friendly recipe together",
        emoji="📋",
        category="creative",
        age_groups=["early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="long",
        energy="low",
        materials="kitchen",
        interests=["cooking", "reading"],
        tags=["following-instructions", "measuring", "skills"],
        adult_supervision=True,
        popularity_score=81,
    ),
    create_activity(
        id="cook_009",
        title="Ice Cream Sundaes",
        description="Build custom ice cream sundaes with toppings",
        emoji="🍨",
        category="creative",
        age_groups=["toddler", "preschool", "early_elementary", "late_elementary", "middle_school", "high_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="kitchen",
        interests=["cooking"],
        tags=["dessert", "customizable", "treat"],
        popularity_score=91,
    ),
    create_activity(
        id="cook_010",
        title="Trail Mix Making",
        description="Create custom trail mix with nuts, fruits, and treats",
        emoji="🥜",
        category="creative",
        age_groups=["preschool", "early_elementary", "late_elementary", "middle_school"],
        location="indoor",
        duration="short",
        energy="low",
        materials="kitchen",
        interests=["cooking"],
        tags=["snack", "healthy", "customizable"],
        popularity_score=76,
    ),
]


def get_all_activities() -> list[dict]:
    """Get all activities."""
    return ACTIVITIES


def get_activity_by_id(activity_id: str) -> dict | None:
    """Get activity by ID."""
    for activity in ACTIVITIES:
        if activity["id"] == activity_id:
            return activity
    return None


def get_activity_count() -> int:
    """Get total activity count."""
    return len(ACTIVITIES)
